# Generated by Django 4.0.2 on 2022-04-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_name', models.CharField(max_length=255)),
                ('shirt_brand', models.CharField(choices=[], default='nike', max_length=255)),
                ('shirt_price', models.FloatField()),
                ('shirt_color', models.CharField(choices=[], default='black', max_length=10)),
                ('shirt_size', models.CharField(choices=[], default='m', max_length=2)),
            ],
        ),
    ]
