# Generated by Django 4.0.2 on 2022-04-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0002_alter_shirt_shirt_brand_alter_shirt_shirt_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='shirt_brand',
            field=models.CharField(choices=[(0, 'nike'), (1, 'adidas'), (2, 'olympikus'), (3, 'mizuno')], default='nike', max_length=255),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='shirt_color',
            field=models.CharField(choices=[(0, 'black'), (1, 'white'), (2, 'blue'), (3, 'green')], default='black', max_length=10),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='shirt_size',
            field=models.CharField(choices=[(0, 'pp'), (1, 'p'), (2, 'm'), (3, 'g'), (4, 'gg')], default='m', max_length=2),
        ),
    ]
