# Generated by Django 4.0.2 on 2022-04-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0004_alter_shirt_shirt_brand_alter_shirt_shirt_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='shirt_brand',
            field=models.IntegerField(choices=[(0, 'nike'), (1, 'adidas'), (2, 'olympikus'), (3, 'mizuno')], default='nike'),
        ),
    ]
