# Generated by Django 4.0.2 on 2022-04-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0005_alter_shirt_shirt_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='shirt_brand',
            field=models.CharField(choices=[('NIKE', 'nike'), ('ADIDAS', 'adidas'), ('OLYMPIKUS', 'olympikus'), ('MIZUNO', 'mizuno')], max_length=255),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='shirt_color',
            field=models.CharField(choices=[('BLACK', 'black'), ('WHITE', 'white'), ('BLUE', 'blue'), ('GREEN', 'green')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='shirt_size',
            field=models.CharField(choices=[('PP', 'pp'), ('P', 'p'), ('M', 'm'), ('G', 'g'), ('GG', 'gg')], max_length=2),
        ),
    ]
