# Generated by Django 4.0.2 on 2022-04-04 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0008_alter_purchase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitems',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shirt.purchase'),
        ),
    ]
