# Generated by Django 4.0.2 on 2022-04-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0015_shirt_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shirt',
            old_name='quantity',
            new_name='shirt_quantity',
        ),
    ]
