# Generated by Django 4.0.2 on 2022-04-13 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0016_rename_quantity_shirt_shirt_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shirt',
            old_name='shirt_quantity',
            new_name='stock',
        ),
    ]
